# -*- coding: utf-8 -*-
"""cie1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gBMUjqrBDJXFWzSiGTmvjeLyQwdNwkks
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
df=pd.read_csv('/content/mtcars12.csv')
sns.histplot(df['mpg'],bins=10,color='blue',alpha=0.7)
plt.xlabel('mpg')
plt.ylabel('frequency')
plt.title('histogram')
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
df=pd.read_csv('/content/mtcars12.csv')
sns.scatterplot(x='mpg',y='wt',data=df)
plt.xlabel('mpg')
plt.ylabel('wt')
plt.title('scatterplot')
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
df=pd.read_csv('/content/mtcars12.csv')
sns.boxplot(x='mpg',y='wt',data=df)
plt.xlabel('mpg')
plt.ylabel('wt')
plt.title('boxplot')
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
df = pd.read_csv('/content/mtcars12.csv')
sns.barplot(x='mpg', y='wt', data=df)
plt.xlabel('mpg')
plt.ylabel('wt')
plt.title('Barplot')
plt.show()